version: "3"

services:

    db:
        container_name: sqlx-playground
        image: postgres:11-alpine
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: pass
            POSTGRES_DB: server
        ports:
        - "2345:5432"
